"use client";

import { useState } from "react";

export default function Home() {
  const [subject, setSubject] = useState("");
  const [faculty, setFaculty] = useState("");
  const [topic, setTopic] = useState("");
  const [className, setClassName] = useState("");
  const [lessonPlan, setLessonPlan] = useState("");

  const generateLessonPlan = () => {
    const content = `
==============================
        LESSON PLAN
==============================

Faculty Name : ${faculty}

Subject      : ${subject}

Topic        : ${topic}

Class        : ${className}

-----------------------------------------
Learning Objectives
-----------------------------------------

1. Students understand the concept of ${topic}

2. Students participate actively in classroom discussion

3. Students improve analytical and communication skills

-----------------------------------------
Teaching Methodology
-----------------------------------------

• Introduction of topic
• Explanation with examples
• Blackboard interaction
• Student activity
• Recap and questioning

-----------------------------------------
Teaching Learning Materials
-----------------------------------------

• Blackboard
• Textbook
• Charts / PPT
• Classroom Discussion

-----------------------------------------
Assessment
-----------------------------------------

• Oral Questions
• Class Interaction
• Short Activity

-----------------------------------------
Conclusion
-----------------------------------------

The lesson was completed successfully and students understood the concept effectively.

==============================
Generated by Chandu AI Educator
==============================
`;

    setLessonPlan(content);
  };

  const downloadLessonPlan = () => {
    const blob = new Blob([lessonPlan], {
      type: "text/plain;charset=utf-8",
    });

    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "LessonPlan.txt";
    link.click();
  };

  return (
    <main
      style={{
        minHeight: "100vh",
        background: "#071126",
        padding: "40px",
        color: "white",
        fontFamily: "Arial",
      }}
    >
      <div
        style={{
          maxWidth: "900px",
          margin: "auto",
          background: "#0b1730",
          padding: "30px",
          borderRadius: "20px",
          border: "2px solid #00d9ff",
        }}
      >
        <h1
          style={{
            textAlign: "center",
            color: "#00d9ff",
            marginBottom: "30px",
          }}
        >
          Chandu AI Educator
        </h1>

        <input
          placeholder="Subject"
          value={subject}
          onChange={(e) => setSubject(e.target.value)}
          style={inputStyle}
        />

        <input
          placeholder="Faculty Name"
          value={faculty}
          onChange={(e) => setFaculty(e.target.value)}
          style={inputStyle}
        />

        <input
          placeholder="Topic"
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          style={inputStyle}
        />

        <input
          placeholder="Class"
          value={className}
          onChange={(e) => setClassName(e.target.value)}
          style={inputStyle}
        />

        <button
          onClick={generateLessonPlan}
          style={buttonStyle}
        >
          Generate Lesson Plan
        </button>

        {lessonPlan && (
          <>
            <textarea
              value={lessonPlan}
              readOnly
              style={{
                width: "100%",
                height: "400px",
                marginTop: "30px",
                padding: "20px",
                borderRadius: "12px",
                background: "#000",
                color: "#00ffcc",
                fontSize: "16px",
              }}
            />

            <button
              onClick={downloadLessonPlan}
              style={{
                ...buttonStyle,
                background: "#00cc44",
                marginTop: "20px",
              }}
            >
              Download Lesson Plan
            </button>
          </>
        )}
      </div>
    </main>
  );
}

const inputStyle = {
  width: "100%",
  padding: "18px",
  marginBottom: "20px",
  borderRadius: "12px",
  border: "1px solid #00d9ff",
  background: "#000",
  color: "white",
  fontSize: "18px",
};

const buttonStyle = {
  width: "100%",
  padding: "18px",
  borderRadius: "12px",
  border: "none",
  background: "#00d9ff",
  color: "black",
  fontSize: "22px",
  fontWeight: "bold" as const,
  cursor: "pointer",
};